In [1]:
import yfinance as yf
import pandas as pd

wti = yf.download('CL=F', period="5y")
brent = yf.download('BZ=F', period="5y")

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [2]:
wti.head()

Price           Close       High        Low       Open  Volume
Ticker           CL=F       CL=F       CL=F       CL=F    CL=F
Date
2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
2021-05-28  66.320000  67.519997  66.169998  66.949997  390461
2021-06-01  67.720001  68.870003  66.410004  66.680000  570985
2021-06-02  68.830002  69.000000  67.779999  67.989998  332995

In [3]:
wti.tail()

Price            Close        High         Low        Open  Volume
Ticker            CL=F        CL=F        CL=F        CL=F    CL=F
Date
2026-05-19  107.769997  109.239998  106.760002  107.110001  206472
2026-05-20   98.260002  104.449997   96.940002  104.120003  320034
2026-05-21   96.349998  102.660004   95.760002   98.949997  345482
2026-05-22   96.599998   99.430000   94.730003   98.000000  261142
2026-05-26   93.309998   93.900002   89.410004   93.879997  161584

Question i encountered at first sight

why the opening price of next day's trade is diffrent from closing price of previous day's trade?

In [4]:
wti[['Open','Close']].head(10)

Price            Open      Close
Ticker           CL=F       CL=F
Date
2021-05-26  66.040001  66.209999
2021-05-27  66.160004  66.849998
2021-05-28  66.949997  66.320000
2021-06-01  66.680000  67.720001
2021-06-02  67.989998  68.830002
2021-06-03  68.760002  68.809998
2021-06-04  68.910004  69.620003
2021-06-07  69.519997  69.230003
2021-06-08  69.290001  70.050003
2021-06-09  70.010002  69.959999

Answer to the above question is- 
The price difference between the previous day’s closing price and the current day’s opening price is called an 'overnight gap', caused by new market information and trading sentiment outside the regular session/offical time.

Globally important assets like crude oil, currencies, gold, and cryptocurrencies trade nearly 24/7 because worldwide demand, economic activity, and market participation continue across different time zones.
And oil is highly demand assest to the world.

In [5]:
wti.describe()

Price         Close         High          Low         Open        Volume
Ticker         CL=F         CL=F         CL=F         CL=F          CL=F
count   1257.000000  1257.000000  1257.000000  1257.000000  1.257000e+03
mean      77.880509    79.349308    76.408202    77.932761  3.208802e+05
std       13.085440    13.711742    12.459508    13.118951  1.269695e+05
min       55.270000    56.700001    54.980000    55.230000  0.000000e+00
25%       69.160004    70.180000    67.949997    69.230003  2.595400e+05
50%       75.660004    77.089996    74.269997    75.739998  3.179390e+05
75%       83.570000    84.919998    82.150002    83.580002  3.784730e+05
max      123.699997   130.500000   120.790001   124.660004  1.107193e+06

Then what is the use of close and open in these assests?

Because stock exchanges historically needed standarized session:
1. centralized matching
2. settlement
3. regulation
4. fairness
5. liquidity concentration

Imagine this chaos:
One analyst starts day at 12 AM
Another at 4 AM
Another at London open
Another at New York open.

In [6]:
wti.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1257 entries, 2021-05-26 to 2026-05-26
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, CL=F)   1257 non-null   float64
 1   (High, CL=F)    1257 non-null   float64
 2   (Low, CL=F)     1257 non-null   float64
 3   (Open, CL=F)    1257 non-null   float64
 4   (Volume, CL=F)  1257 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 58.9 KB

Data Modeling

Why Flattening is important?
Flattening makes:
1. code cleaner
2. analysis easier
3. plotting easier
4. ML preprocessing easier
5. debugging easier

When you should NOT flatten? 
Keep MultiIndex when hierarchy matters. Now MultiIndex becomes powerful for:
1. portfolio analysis
2. sector comparison
3. multi-asset correlation
4. grouped operations

In [7]:
wti.columns = wti.columns.get_level_values(0)
wti.head()

Price           Close       High        Low       Open  Volume
Date
2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
2021-05-28  66.320000  67.519997  66.169998  66.949997  390461
2021-06-01  67.720001  68.870003  66.410004  66.680000  570985
2021-06-02  68.830002  69.000000  67.779999  67.989998  332995

In [8]:
# Price is a column name 
wti.columns.name = None
wti.head()

                Close       High        Low       Open  Volume
Date
2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
2021-05-28  66.320000  67.519997  66.169998  66.949997  390461
2021-06-01  67.720001  68.870003  66.410004  66.680000  570985
2021-06-02  68.830002  69.000000  67.779999  67.989998  332995

Index - index used as basline to compare

In [9]:
wti.reset_index(inplace=True)
wti.head()

        Date      Close       High        Low       Open  Volume
0 2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
1 2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
2 2021-05-28  66.320000  67.519997  66.169998  66.949997  390461
3 2021-06-01  67.720001  68.870003  66.410004  66.680000  570985
4 2021-06-02  68.830002  69.000000  67.779999  67.989998  332995

In [10]:
wti.set_index('Date', inplace=True)
wti.head()

                Close       High        Low       Open  Volume
Date
2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
2021-05-28  66.320000  67.519997  66.169998  66.949997  390461
2021-06-01  67.720001  68.870003  66.410004  66.680000  570985
2021-06-02  68.830002  69.000000  67.779999  67.989998  332995

In [11]:
#again flatten column
wti.reset_index(inplace=True)
wti.columns.name = None
wti.head()

        Date      Close       High        Low       Open  Volume
0 2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
1 2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
2 2021-05-28  66.320000  67.519997  66.169998  66.949997  390461
3 2021-06-01  67.720001  68.870003  66.410004  66.680000  570985
4 2021-06-02  68.830002  69.000000  67.779999  67.989998  332995

In [13]:
# standarize all column to lower
wti.columns = wti.columns.str.lower()
wti.head()

        date      close       high        low       open  volume
0 2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
1 2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
2 2021-05-28  66.320000  67.519997  66.169998  66.949997  390461
3 2021-06-01  67.720001  68.870003  66.410004  66.680000  570985
4 2021-06-02  68.830002  69.000000  67.779999  67.989998  332995

Problem Statement - Analysis of oil prices

My First Real Feature Engineering

In [15]:
wti[["open", "close"]].head(10)

        open      close
0  66.040001  66.209999
1  66.160004  66.849998
2  66.949997  66.320000
3  66.680000  67.720001
4  67.989998  68.830002
5  68.760002  68.809998
6  68.910004  69.620003
7  69.519997  69.230003
8  69.290001  70.050003
9  70.010002  69.959999

Finding the gap

In [17]:
# previous close as a new column - so that when we pull entire single row it will give prev_close 
wti['prev_close'] = wti['close'].shift(1)
wti.head()

        date      close       high        low       open  volume  prev_close
0 2021-05-26  66.209999  66.430000  65.250000  66.040001  376207         NaN
1 2021-05-27  66.849998  66.919998  65.470001  66.160004  337542   66.209999
2 2021-05-28  66.320000  67.519997  66.169998  66.949997  390461   66.849998
3 2021-06-01  67.720001  68.870003  66.410004  66.680000  570985   66.320000
4 2021-06-02  68.830002  69.000000  67.779999  67.989998  332995   67.720001

In [18]:
# daily gap
wti['gap'] = wti['open'] - wti['prev_close']
wti['gap'].head(5)

0         NaN
1   -0.049995
2    0.099998
3    0.360001
4    0.269997
Name: gap, dtype: float64

In [19]:
# 2days_gap
wti['2daysago_close'] = wti['close'].shift(2)
wti['2days_gap'] = wti['open'] - wti['2daysago_close']
wti.head()

,date,close,high,low,open,volume,prev_close,gap,2daysago_close,2days_gap
0,2021-05-26,66.209999,66.430000,65.250000,66.040001,376207,NaN,NaN,NaN,NaN
1,2021-05-27,66.849998,66.919998,65.470001,66.160004,337542,66.209999,-0.049995,NaN,NaN
2,2021-05-28,66.320000,67.519997,66.169998,66.949997,390461,66.849998,0.099998,66.209999,0.739998
3,2021-06-01,67.720001,68.870003,66.410004,66.680000,570985,66.320000,0.360001,66.849998,-0.169998
4,2021-06-02,68.830002,69.000000,67.779999,67.989998,332995,67.720001,0.269997,66.320000,1.669998

In [33]:
#bigger value in gap
wti[['gap', '2days_gap']].max()

gap           7.980003
2days_gap    16.989998
dtype: float64

In [35]:
#bigger value with row
wti.loc[wti['gap'].idxmax()]

date              2026-03-02 00:00:00
close                       71.230003
high                        75.330002
low                         69.199997
open                             75.0
volume                         881329
prev_close                  67.019997
gap                          7.980003
2daysago_close              65.209999
2days_gap                    9.790001
Name: 1197, dtype: object