In [93]:
import yfinance as yf
import pandas as pd

wti = yf.download('CL=F', period="5y")
brent = yf.download('BZ=F', period="5y")

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [94]:
wti.head()

Price           Close       High        Low       Open  Volume
Ticker           CL=F       CL=F       CL=F       CL=F    CL=F
Date
2021-05-24  66.050003  66.139999  63.630001  63.869999  466647
2021-05-25  66.070000  66.510002  65.410004  66.019997  497394
2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
2021-05-28  66.320000  67.519997  66.169998  66.949997  390461

In [95]:
wti.tail()

Price            Close        High         Low        Open  Volume
Ticker            CL=F        CL=F        CL=F        CL=F    CL=F
Date
2026-05-18  108.660004  109.470001  102.650002  106.000000  117910
2026-05-19  107.769997  109.239998  106.760002  107.110001  206472
2026-05-20   98.260002  104.449997   96.940002  104.120003  320034
2026-05-21   96.349998  102.660004   95.760002   98.949997  320034
2026-05-22   97.809998   99.430000   95.459999   98.000000  116126

Question i encountered at first sight

why the opening price of next day's trade is diffrent from closing price of previous day's trade?

In [96]:
wti[['Open','Close']].head(10)

Price            Open      Close
Ticker           CL=F       CL=F
Date
2021-05-24  63.869999  66.050003
2021-05-25  66.019997  66.070000
2021-05-26  66.040001  66.209999
2021-05-27  66.160004  66.849998
2021-05-28  66.949997  66.320000
2021-06-01  66.680000  67.720001
2021-06-02  67.989998  68.830002
2021-06-03  68.760002  68.809998
2021-06-04  68.910004  69.620003
2021-06-07  69.519997  69.230003

Answer to the above question is- 
The price difference between the previous day’s closing price and the current day’s opening price is called an 'overnight gap', caused by new market information and trading sentiment outside the regular session/offical time.

Globally important assets like crude oil, currencies, gold, and cryptocurrencies trade nearly 24/7 because worldwide demand, economic activity, and market participation continue across different time zones.
And oil is highly demand assest to the world.

In [103]:
wti.describe()

Price        Close         High          Low         Open        Volume
count  1258.000000  1258.000000  1258.000000  1258.000000  1.258000e+03
mean     77.850413    79.317035    76.379547    77.899436  3.211275e+05
std      13.082880    13.709952    12.459067    13.116278  1.271216e+05
min      55.270000    56.700001    54.980000    55.230000  0.000000e+00
25%      69.120001    70.150002    67.927498    69.187500  2.595535e+05
50%      75.599998    77.089996    74.235001    75.699997  3.180695e+05
75%      83.527500    84.887499    82.107500    83.537500  3.790180e+05
max     123.699997   130.500000   120.790001   124.660004  1.107193e+06

Then what is the use of close and open in these assests?

Because stock exchanges historically needed standarized session:
1. centralized matching
2. settlement
3. regulation
4. fairness
5. liquidity concentration

Imagine this chaos:
One analyst starts day at 12 AM
Another at 4 AM
Another at London open
Another at New York open.

In [108]:
wti.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1258 entries, 2021-05-24 to 2026-05-22
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   1258 non-null   float64
 1   High    1258 non-null   float64
 2   Low     1258 non-null   float64
 3   Open    1258 non-null   float64
 4   Volume  1258 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 59.0 KB

Data Modeling

Why Flattening is important?
Flattening makes:
1. code cleaner
2. analysis easier
3. plotting easier
4. ML preprocessing easier
5. debugging easier

When you should NOT flatten? 
Keep MultiIndex when hierarchy matters. Now MultiIndex becomes powerful for:
1. portfolio analysis
2. sector comparison
3. multi-asset correlation
4. grouped operations

In [98]:
wti.columns = wti.columns.get_level_values(0)
wti.head()

Price           Close       High        Low       Open  Volume
Date
2021-05-24  66.050003  66.139999  63.630001  63.869999  466647
2021-05-25  66.070000  66.510002  65.410004  66.019997  497394
2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
2021-05-28  66.320000  67.519997  66.169998  66.949997  390461

In [100]:
# Price is a column name 
wti.columns.name = None
wti.head()

                Close       High        Low       Open  Volume
Date
2021-05-24  66.050003  66.139999  63.630001  63.869999  466647
2021-05-25  66.070000  66.510002  65.410004  66.019997  497394
2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
2021-05-28  66.320000  67.519997  66.169998  66.949997  390461

In [102]:
wti.columns.name = "Price"
wti.head()

Price           Close       High        Low       Open  Volume
Date
2021-05-24  66.050003  66.139999  63.630001  63.869999  466647
2021-05-25  66.070000  66.510002  65.410004  66.019997  497394
2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
2021-05-28  66.320000  67.519997  66.169998  66.949997  390461

Index

In [83]:
wti.reset_index(inplace=True)
wti.head()

Price       Date      Close       High        Low       Open  Volume
0     2021-05-24  66.050003  66.139999  63.630001  63.869999  466647
1     2021-05-25  66.070000  66.510002  65.410004  66.019997  497394
2     2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
3     2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
4     2021-05-28  66.320000  67.519997  66.169998  66.949997  390461

In [84]:
wti.set_index('Date', inplace=True)
wti.head()

Price           Close       High        Low       Open  Volume
Date
2021-05-24  66.050003  66.139999  63.630001  63.869999  466647
2021-05-25  66.070000  66.510002  65.410004  66.019997  497394
2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
2021-05-28  66.320000  67.519997  66.169998  66.949997  390461

In [86]:
#again flatten column
wti.reset_index(inplace=True)
wti.head()

Price  index       Date      Close       High        Low       Open  Volume
0          0 2021-05-24  66.050003  66.139999  63.630001  63.869999  466647
1          1 2021-05-25  66.070000  66.510002  65.410004  66.019997  497394
2          2 2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
3          3 2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
4          4 2021-05-28  66.320000  67.519997  66.169998  66.949997  390461