In [1]:
import yfinance as yf
import pandas as pd

wti = yf.download('CL=F', period="5y")
brent = yf.download('BZ=F', period="5y")

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [2]:
wti.head()

Price           Close       High        Low       Open  Volume
Ticker           CL=F       CL=F       CL=F       CL=F    CL=F
Date
2021-05-25  66.070000  66.510002  65.410004  66.019997  497394
2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
2021-05-28  66.320000  67.519997  66.169998  66.949997  390461
2021-06-01  67.720001  68.870003  66.410004  66.680000  570985

In [3]:
wti.tail()

Price            Close        High         Low        Open  Volume
Ticker            CL=F        CL=F        CL=F        CL=F    CL=F
Date
2026-05-19  107.769997  109.239998  106.760002  107.110001  206472
2026-05-20   98.260002  104.449997   96.940002  104.120003  320034
2026-05-21   96.349998  102.660004   95.760002   98.949997  345482
2026-05-22   96.599998   99.430000   94.730003   98.000000  345482
2026-05-25   96.599998   93.900002   90.320000   93.879997   94985

Question i encountered at first sight

why the opening price of next day's trade is diffrent from closing price of previous day's trade?

In [4]:
wti[['Open','Close']].head(10)

Price            Open      Close
Ticker           CL=F       CL=F
Date
2021-05-25  66.019997  66.070000
2021-05-26  66.040001  66.209999
2021-05-27  66.160004  66.849998
2021-05-28  66.949997  66.320000
2021-06-01  66.680000  67.720001
2021-06-02  67.989998  68.830002
2021-06-03  68.760002  68.809998
2021-06-04  68.910004  69.620003
2021-06-07  69.519997  69.230003
2021-06-08  69.290001  70.050003

Answer to the above question is- 
The price difference between the previous day’s closing price and the current day’s opening price is called an 'overnight gap', caused by new market information and trading sentiment outside the regular session/offical time.

Globally important assets like crude oil, currencies, gold, and cryptocurrencies trade nearly 24/7 because worldwide demand, economic activity, and market participation continue across different time zones.
And oil is highly demand assest to the world.

In [5]:
wti.describe()

Price         Close         High          Low         Open        Volume
Ticker         CL=F         CL=F         CL=F         CL=F          CL=F
count   1258.000000  1258.000000  1258.000000  1258.000000  1.258000e+03
mean      77.873736    79.339102    76.400183    77.923291  3.210346e+05
std       13.087889    13.711067    12.459193    13.118032  1.270875e+05
min       55.270000    56.700001    54.980000    55.230000  0.000000e+00
25%       69.152502    70.157501    67.949997    69.215000  2.595535e+05
50%       75.645000    77.089996    74.254997    75.719997  3.180695e+05
75%       83.562500    84.912498    82.140001    83.570002  3.785960e+05
max      123.699997   130.500000   120.790001   124.660004  1.107193e+06

Then what is the use of close and open in these assests?

Because stock exchanges historically needed standarized session:
1. centralized matching
2. settlement
3. regulation
4. fairness
5. liquidity concentration

Imagine this chaos:
One analyst starts day at 12 AM
Another at 4 AM
Another at London open
Another at New York open.

In [6]:
wti.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1258 entries, 2021-05-25 to 2026-05-25
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, CL=F)   1258 non-null   float64
 1   (High, CL=F)    1258 non-null   float64
 2   (Low, CL=F)     1258 non-null   float64
 3   (Open, CL=F)    1258 non-null   float64
 4   (Volume, CL=F)  1258 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 59.0 KB

Data Modeling

Why Flattening is important?
Flattening makes:
1. code cleaner
2. analysis easier
3. plotting easier
4. ML preprocessing easier
5. debugging easier

When you should NOT flatten? 
Keep MultiIndex when hierarchy matters. Now MultiIndex becomes powerful for:
1. portfolio analysis
2. sector comparison
3. multi-asset correlation
4. grouped operations

In [7]:
wti.columns = wti.columns.get_level_values(0)
wti.head()

Price           Close       High        Low       Open  Volume
Date
2021-05-25  66.070000  66.510002  65.410004  66.019997  497394
2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
2021-05-28  66.320000  67.519997  66.169998  66.949997  390461
2021-06-01  67.720001  68.870003  66.410004  66.680000  570985

In [8]:
# Price is a column name 
wti.columns.name = None
wti.head()

                Close       High        Low       Open  Volume
Date
2021-05-25  66.070000  66.510002  65.410004  66.019997  497394
2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
2021-05-28  66.320000  67.519997  66.169998  66.949997  390461
2021-06-01  67.720001  68.870003  66.410004  66.680000  570985

In [9]:
wti.columns.name = "Price"
wti.head()

Price           Close       High        Low       Open  Volume
Date
2021-05-25  66.070000  66.510002  65.410004  66.019997  497394
2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
2021-05-28  66.320000  67.519997  66.169998  66.949997  390461
2021-06-01  67.720001  68.870003  66.410004  66.680000  570985

Index

In [10]:
wti.reset_index(inplace=True)
wti.head()

Price       Date      Close       High        Low       Open  Volume
0     2021-05-25  66.070000  66.510002  65.410004  66.019997  497394
1     2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
2     2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
3     2021-05-28  66.320000  67.519997  66.169998  66.949997  390461
4     2021-06-01  67.720001  68.870003  66.410004  66.680000  570985

In [11]:
wti.set_index('Date', inplace=True)
wti.head()

Price           Close       High        Low       Open  Volume
Date
2021-05-25  66.070000  66.510002  65.410004  66.019997  497394
2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
2021-05-28  66.320000  67.519997  66.169998  66.949997  390461
2021-06-01  67.720001  68.870003  66.410004  66.680000  570985

In [12]:
#again flatten column
wti.reset_index(inplace=True)
wti.head()

Price       Date      Close       High        Low       Open  Volume
0     2021-05-25  66.070000  66.510002  65.410004  66.019997  497394
1     2021-05-26  66.209999  66.430000  65.250000  66.040001  376207
2     2021-05-27  66.849998  66.919998  65.470001  66.160004  337542
3     2021-05-28  66.320000  67.519997  66.169998  66.949997  390461
4     2021-06-01  67.720001  68.870003  66.410004  66.680000  570985

Your First Real Feature Engineering

In [20]:
wti[["Open", "Close"]].head(10)

Price       Open      Close
0      66.019997  66.070000
1      66.040001  66.209999
2      66.160004  66.849998
3      66.949997  66.320000
4      66.680000  67.720001
5      67.989998  68.830002
6      68.760002  68.809998
7      68.910004  69.620003
8      69.519997  69.230003
9      69.290001  70.050003

Finding the gap

In [23]:
# previous day gap
wti['Gap'] = wti['Open'] - wti['Close'].shift(1)
wti['Gap'].head(5)

0         NaN
1   -0.029999
2   -0.049995
3    0.099998
4    0.360001
Name: Gap, dtype: float64

In [24]:
# day before yesterday gap
wti['Close_2days_ago'] = wti['Close'].shift(2)
wti['2days_gap'] = wti['Open'] - wti['Close_2days_ago']
wti['2days_gap'].head(5)

0         NaN
1         NaN
2    0.090004
3    0.739998
4   -0.169998
Name: 2days_gap, dtype: float64

In [22]:
#i am trying to find if there any gap has biger value 
wti['Gap']

0            NaN
1      -0.029999
2      -0.049995
3       0.099998
4       0.360001
          ...
1253   -1.550003
1254   -3.649994
1255    0.689995
1256    1.650002
1257   -2.720001
Name: Gap, Length: 1258, dtype: float64